# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvm',
            name='datetime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tvm',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
