# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvm', '0003_auto_20170609_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvm',
            name='name',
            field=models.CharField(choices=[(0, '360自行车'), (1, 'VR'), (2, '全息音效')], max_length=20, verbose_name='项目名称'),
        ),
    ]
