# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvm', '0004_auto_20170609_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvm',
            name='date',
            field=models.CharField(default='20101010', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvm',
            name='datetime',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tvm',
            name='name',
            field=models.IntegerField(choices=[(0, '360自行车'), (1, 'VR'), (2, '全息音效')], verbose_name='项目名称'),
        ),
    ]
