# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvm', '0005_auto_20170609_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvm',
            name='name',
            field=models.CharField(choices=[('360', '360自行车'), ('VR', 'VR'), ('FULLSOUND', '全息音效')], max_length=20, verbose_name='项目名称'),
        ),
    ]
